version: '2.1'

services:
  nuxt-contentstack:
    image: nuxt-contentstack
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js